version: "3.5"
volumes:
  web:

services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    restart: always
    networks:
      - custom
  web:
    build:
      context: ./
    command: >
      sh -c "poetry run flask --app source/main run --host 0.0.0.0 --port 8080
              "
    container_name: "web"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - web:/usr/flask-redis-app/
    networks:
      - custom

networks:
  custom:
    driver: bridge
    name: custom
